auth:
  jwt_secret: "sraka"

tun:
  mtu: 1420 # Всегда должен быть меньше наименьшего транспорта
  iface_in_name: "liberator"
  iface_out_name: "amn0"
router:
  global_cidr: 10.0.0.0/8
  cidr: "10.8.0.1/16" # Addr here corresponds to gateway(vpn server host), dns server launched here
  transports:
    awg:
      type: "awg"

      mtu: 1372
      listen_port: 2200
      private_key: "2f878af7e796bb392306fc4e1379b870b53de2c0ed89a086fbc059f17c5d7829" # 32bytes hex encoded key
      watchdog_interval: "30s"

      h1: "1245955480-1579617642"
      h2: "1827874969-1854585193"
      h3: "2137919667-2143439009"
      h4: "2147159423-2147402519"

      jc: 5
      jmin: 70
      jmax: 120

      s1: 48
      s2: 27
      s3: 30
      s4: 7

mesh:
  listen_addr: ":9000"
  bootstrap_addrs:
    - "localhost:9001"
  peers_store: "peers.json"
  discovery_interval: 30s 
  rtt_update_interval: 10s
  cert: "./certs/node_0.crt"
  key: "./certs/node_0.key"
  root_cert: "./certs/root.crt"

database:
  file: "./database.sqlite"

metrics:
  listen_addr: ":9090"


api:
  grpc:
    listen_addr: ":9001"
