auth:
  jwt_secret: "sraka"


bridge:
  bridge1:
    cidr: "10.9.0.1/16" # Addr here corresponds to gateway(vpn server host), dns server launched here
    mtu: 1376
    dns: "1.1.1.1" # Where to proxy dns requests
    ingresses:
      liberator0:
        type: "liberator"
        listen_addr: ":2101"
        cert: "./certs/node_1.crt"
        key: "./certs/node_1.key"
    egress:
      iface_in_name: "liberator1"
      iface_out_name: "amn0"

mesh:
  listen_addr: ":9001"
  bootstrap_addrs:
    - "localhost:9000"
  peers_store: "peers.json"
  discovery_interval: 30s 
  rtt_update_interval: 10s
  cert: "./certs/node_1.crt"
  key: "./certs/node_1.key"
  root_cert: "./certs/root.crt"

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "HermanFuLLer"
  database: "default"


metrics:
  listen_addr: ":9091"