// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/meshrouting/proto/meshrouting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_ADD    UpdateType = 0
	UpdateType_REMOVE UpdateType = 1
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	UpdateType_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_pkg_mesh_meshrouting_proto_meshrouting_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{0}
}

type UserConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{0}
}

func (x *UserConnection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserConnection) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *UserConnection) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UserConnectionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *UserConnection        `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Type          UpdateType             `protobuf:"varint,2,opt,name=type,proto3,enum=proto.UpdateType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnectionUpdate) Reset() {
	*x = UserConnectionUpdate{}
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnectionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnectionUpdate) ProtoMessage() {}

func (x *UserConnectionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnectionUpdate.ProtoReflect.Descriptor instead.
func (*UserConnectionUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{1}
}

func (x *UserConnectionUpdate) GetInfo() *UserConnection {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserConnectionUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_ADD
}

type UsersConnectionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*UserConnection      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersConnectionsList) Reset() {
	*x = UsersConnectionsList{}
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersConnectionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersConnectionsList) ProtoMessage() {}

func (x *UsersConnectionsList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersConnectionsList.ProtoReflect.Descriptor instead.
func (*UsersConnectionsList) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{2}
}

func (x *UsersConnectionsList) GetConnections() []*UserConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_pkg_mesh_meshrouting_proto_meshrouting_proto protoreflect.FileDescriptor

const file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDesc = "" +
	"\n" +
	",pkg/mesh/meshrouting/proto/meshrouting.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\x0eUserConnection\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"h\n" +
	"\x14UserConnectionUpdate\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x15.proto.UserConnectionR\x04info\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.proto.UpdateTypeR\x04type\"O\n" +
	"\x14UsersConnectionsList\x127\n" +
	"\vconnections\x18\x01 \x03(\v2\x15.proto.UserConnectionR\vconnections*!\n" +
	"\n" +
	"UpdateType\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x012\xa7\x01\n" +
	"\x12MeshRoutingService\x12K\n" +
	"\x14SendConnectionUpdate\x12\x1b.proto.UserConnectionUpdate\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rPullFullTable\x12\x16.google.protobuf.Empty\x1a\x1b.proto.UsersConnectionsListB\tZ\a./protob\x06proto3"

var (
	file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescOnce sync.Once
	file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescData []byte
)

func file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescGZIP() []byte {
	file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDesc), len(file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDesc)))
	})
	return file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDescData
}

var file_pkg_mesh_meshrouting_proto_meshrouting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_mesh_meshrouting_proto_meshrouting_proto_goTypes = []any{
	(UpdateType)(0),              // 0: proto.UpdateType
	(*UserConnection)(nil),       // 1: proto.UserConnection
	(*UserConnectionUpdate)(nil), // 2: proto.UserConnectionUpdate
	(*UsersConnectionsList)(nil), // 3: proto.UsersConnectionsList
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_pkg_mesh_meshrouting_proto_meshrouting_proto_depIdxs = []int32{
	1, // 0: proto.UserConnectionUpdate.info:type_name -> proto.UserConnection
	0, // 1: proto.UserConnectionUpdate.type:type_name -> proto.UpdateType
	1, // 2: proto.UsersConnectionsList.connections:type_name -> proto.UserConnection
	2, // 3: proto.MeshRoutingService.SendConnectionUpdate:input_type -> proto.UserConnectionUpdate
	4, // 4: proto.MeshRoutingService.PullFullTable:input_type -> google.protobuf.Empty
	4, // 5: proto.MeshRoutingService.SendConnectionUpdate:output_type -> google.protobuf.Empty
	3, // 6: proto.MeshRoutingService.PullFullTable:output_type -> proto.UsersConnectionsList
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_mesh_meshrouting_proto_meshrouting_proto_init() }
func file_pkg_mesh_meshrouting_proto_meshrouting_proto_init() {
	if File_pkg_mesh_meshrouting_proto_meshrouting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDesc), len(file_pkg_mesh_meshrouting_proto_meshrouting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_meshrouting_proto_meshrouting_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_meshrouting_proto_meshrouting_proto_depIdxs,
		EnumInfos:         file_pkg_mesh_meshrouting_proto_meshrouting_proto_enumTypes,
		MessageInfos:      file_pkg_mesh_meshrouting_proto_meshrouting_proto_msgTypes,
	}.Build()
	File_pkg_mesh_meshrouting_proto_meshrouting_proto = out.File
	file_pkg_mesh_meshrouting_proto_meshrouting_proto_goTypes = nil
	file_pkg_mesh_meshrouting_proto_meshrouting_proto_depIdxs = nil
}
