// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/mesh/peerssync/proto/peerssync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeersSyncService_SubscribeClients_FullMethodName      = "/proto.PeersSyncService/SubscribeClients"
	PeersSyncService_SubscribeClientsRules_FullMethodName = "/proto.PeersSyncService/SubscribeClientsRules"
)

// PeersSyncServiceClient is the client API for PeersSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeersSyncServiceClient interface {
	// Узел подписывается на поток изменений от соседа
	SubscribeClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientEvent], error)
	SubscribeClientsRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientRuleEvent], error)
}

type peersSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeersSyncServiceClient(cc grpc.ClientConnInterface) PeersSyncServiceClient {
	return &peersSyncServiceClient{cc}
}

func (c *peersSyncServiceClient) SubscribeClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeersSyncService_ServiceDesc.Streams[0], PeersSyncService_SubscribeClients_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ClientEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeersSyncService_SubscribeClientsClient = grpc.ServerStreamingClient[ClientEvent]

func (c *peersSyncServiceClient) SubscribeClientsRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientRuleEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeersSyncService_ServiceDesc.Streams[1], PeersSyncService_SubscribeClientsRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ClientRuleEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeersSyncService_SubscribeClientsRulesClient = grpc.ServerStreamingClient[ClientRuleEvent]

// PeersSyncServiceServer is the server API for PeersSyncService service.
// All implementations must embed UnimplementedPeersSyncServiceServer
// for forward compatibility.
type PeersSyncServiceServer interface {
	// Узел подписывается на поток изменений от соседа
	SubscribeClients(*emptypb.Empty, grpc.ServerStreamingServer[ClientEvent]) error
	SubscribeClientsRules(*emptypb.Empty, grpc.ServerStreamingServer[ClientRuleEvent]) error
	mustEmbedUnimplementedPeersSyncServiceServer()
}

// UnimplementedPeersSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeersSyncServiceServer struct{}

func (UnimplementedPeersSyncServiceServer) SubscribeClients(*emptypb.Empty, grpc.ServerStreamingServer[ClientEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeClients not implemented")
}
func (UnimplementedPeersSyncServiceServer) SubscribeClientsRules(*emptypb.Empty, grpc.ServerStreamingServer[ClientRuleEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeClientsRules not implemented")
}
func (UnimplementedPeersSyncServiceServer) mustEmbedUnimplementedPeersSyncServiceServer() {}
func (UnimplementedPeersSyncServiceServer) testEmbeddedByValue()                          {}

// UnsafePeersSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeersSyncServiceServer will
// result in compilation errors.
type UnsafePeersSyncServiceServer interface {
	mustEmbedUnimplementedPeersSyncServiceServer()
}

func RegisterPeersSyncServiceServer(s grpc.ServiceRegistrar, srv PeersSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedPeersSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeersSyncService_ServiceDesc, srv)
}

func _PeersSyncService_SubscribeClients_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeersSyncServiceServer).SubscribeClients(m, &grpc.GenericServerStream[emptypb.Empty, ClientEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeersSyncService_SubscribeClientsServer = grpc.ServerStreamingServer[ClientEvent]

func _PeersSyncService_SubscribeClientsRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeersSyncServiceServer).SubscribeClientsRules(m, &grpc.GenericServerStream[emptypb.Empty, ClientRuleEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeersSyncService_SubscribeClientsRulesServer = grpc.ServerStreamingServer[ClientRuleEvent]

// PeersSyncService_ServiceDesc is the grpc.ServiceDesc for PeersSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeersSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PeersSyncService",
	HandlerType: (*PeersSyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeClients",
			Handler:       _PeersSyncService_SubscribeClients_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeClientsRules",
			Handler:       _PeersSyncService_SubscribeClientsRules_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/mesh/peerssync/proto/peerssync.proto",
}
