// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/peerssync/proto/peerssync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEventType int32

const (
	ClientEventType_CLIENT_EVENT_SYNC         ClientEventType = 0
	ClientEventType_CLIENT_EVENT_CONNECTED    ClientEventType = 1
	ClientEventType_CLIENT_EVENT_DISCONNECTED ClientEventType = 2
)

// Enum value maps for ClientEventType.
var (
	ClientEventType_name = map[int32]string{
		0: "CLIENT_EVENT_SYNC",
		1: "CLIENT_EVENT_CONNECTED",
		2: "CLIENT_EVENT_DISCONNECTED",
	}
	ClientEventType_value = map[string]int32{
		"CLIENT_EVENT_SYNC":         0,
		"CLIENT_EVENT_CONNECTED":    1,
		"CLIENT_EVENT_DISCONNECTED": 2,
	}
)

func (x ClientEventType) Enum() *ClientEventType {
	p := new(ClientEventType)
	*p = x
	return p
}

func (x ClientEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mesh_peerssync_proto_peerssync_proto_enumTypes[0].Descriptor()
}

func (ClientEventType) Type() protoreflect.EnumType {
	return &file_pkg_mesh_peerssync_proto_peerssync_proto_enumTypes[0]
}

func (x ClientEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientEventType.Descriptor instead.
func (ClientEventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescGZIP(), []int{0}
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VirtualIp     uint32                 `protobuf:"varint,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClientInfo) GetVirtualIp() uint32 {
	if x != nil {
		return x.VirtualIp
	}
	return 0
}

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ClientEventType        `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ClientEventType" json:"type,omitempty"`
	Update        *ClientInfo            `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	Dump          []*ClientInfo          `protobuf:"bytes,3,rep,name=dump,proto3" json:"dump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEvent) GetType() ClientEventType {
	if x != nil {
		return x.Type
	}
	return ClientEventType_CLIENT_EVENT_SYNC
}

func (x *ClientEvent) GetUpdate() *ClientInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ClientEvent) GetDump() []*ClientInfo {
	if x != nil {
		return x.Dump
	}
	return nil
}

var File_pkg_mesh_peerssync_proto_peerssync_proto protoreflect.FileDescriptor

const file_pkg_mesh_peerssync_proto_peerssync_proto_rawDesc = "" +
	"\n" +
	"(pkg/mesh/peerssync/proto/peerssync.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\n" +
	"ClientInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\rR\tvirtualIp\"\x8b\x01\n" +
	"\vClientEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.proto.ClientEventTypeR\x04type\x12)\n" +
	"\x06update\x18\x02 \x01(\v2\x11.proto.ClientInfoR\x06update\x12%\n" +
	"\x04dump\x18\x03 \x03(\v2\x11.proto.ClientInfoR\x04dump*c\n" +
	"\x0fClientEventType\x12\x15\n" +
	"\x11CLIENT_EVENT_SYNC\x10\x00\x12\x1a\n" +
	"\x16CLIENT_EVENT_CONNECTED\x10\x01\x12\x1d\n" +
	"\x19CLIENT_EVENT_DISCONNECTED\x10\x022T\n" +
	"\x10PeersSyncService\x12@\n" +
	"\x10SubscribeClients\x12\x16.google.protobuf.Empty\x1a\x12.proto.ClientEvent0\x01B\tZ\a./protob\x06proto3"

var (
	file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescOnce sync.Once
	file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescData []byte
)

func file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescGZIP() []byte {
	file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_peerssync_proto_peerssync_proto_rawDesc), len(file_pkg_mesh_peerssync_proto_peerssync_proto_rawDesc)))
	})
	return file_pkg_mesh_peerssync_proto_peerssync_proto_rawDescData
}

var file_pkg_mesh_peerssync_proto_peerssync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_mesh_peerssync_proto_peerssync_proto_goTypes = []any{
	(ClientEventType)(0),  // 0: proto.ClientEventType
	(*ClientInfo)(nil),    // 1: proto.ClientInfo
	(*ClientEvent)(nil),   // 2: proto.ClientEvent
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_pkg_mesh_peerssync_proto_peerssync_proto_depIdxs = []int32{
	0, // 0: proto.ClientEvent.type:type_name -> proto.ClientEventType
	1, // 1: proto.ClientEvent.update:type_name -> proto.ClientInfo
	1, // 2: proto.ClientEvent.dump:type_name -> proto.ClientInfo
	3, // 3: proto.PeersSyncService.SubscribeClients:input_type -> google.protobuf.Empty
	2, // 4: proto.PeersSyncService.SubscribeClients:output_type -> proto.ClientEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_mesh_peerssync_proto_peerssync_proto_init() }
func file_pkg_mesh_peerssync_proto_peerssync_proto_init() {
	if File_pkg_mesh_peerssync_proto_peerssync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_peerssync_proto_peerssync_proto_rawDesc), len(file_pkg_mesh_peerssync_proto_peerssync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_peerssync_proto_peerssync_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_peerssync_proto_peerssync_proto_depIdxs,
		EnumInfos:         file_pkg_mesh_peerssync_proto_peerssync_proto_enumTypes,
		MessageInfos:      file_pkg_mesh_peerssync_proto_peerssync_proto_msgTypes,
	}.Build()
	File_pkg_mesh_peerssync_proto_peerssync_proto = out.File
	file_pkg_mesh_peerssync_proto_peerssync_proto_goTypes = nil
	file_pkg_mesh_peerssync_proto_peerssync_proto_depIdxs = nil
}
