// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ingress/ingressproto/ingress.proto

package ingressproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_ingress_ingressproto_ingress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingress_ingressproto_ingress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_ingress_ingressproto_ingress_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthorizeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// Tunnel configuration assigned to the client on success.
	AssignedIp    string   `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"` // e.g. "10.8.0.2"
	PrefixLen     uint32   `protobuf:"varint,4,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`   // e.g. 24
	Mtu           uint32   `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`                                // e.g. 1400
	Routes        []string `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`                           // CIDRs to route into the tunnel, e.g. ["0.0.0.0/0"]
	Dns           []string `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`                                 // optional DNS servers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_ingress_ingressproto_ingress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingress_ingressproto_ingress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_ingress_ingressproto_ingress_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AuthorizeResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *AuthorizeResponse) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *AuthorizeResponse) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *AuthorizeResponse) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *AuthorizeResponse) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

var File_ingress_ingressproto_ingress_proto protoreflect.FileDescriptor

const file_ingress_ingressproto_ingress_proto_rawDesc = "" +
	"\n" +
	"\"ingress/ingressproto/ingress.proto\x12\fingressproto\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x10AuthorizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc7\x01\n" +
	"\x11AuthorizeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x04 \x01(\rR\tprefixLen\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\rR\x03mtu\x12\x16\n" +
	"\x06routes\x18\x06 \x03(\tR\x06routes\x12\x10\n" +
	"\x03dns\x18\a \x03(\tR\x03dnsB\t\n" +
	"\a_reason2^\n" +
	"\x0eIngressService\x12L\n" +
	"\tAuthorize\x12\x1e.ingressproto.AuthorizeRequest\x1a\x1f.ingressproto.AuthorizeResponseB\x10Z\x0e./ingressprotob\x06proto3"

var (
	file_ingress_ingressproto_ingress_proto_rawDescOnce sync.Once
	file_ingress_ingressproto_ingress_proto_rawDescData []byte
)

func file_ingress_ingressproto_ingress_proto_rawDescGZIP() []byte {
	file_ingress_ingressproto_ingress_proto_rawDescOnce.Do(func() {
		file_ingress_ingressproto_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingress_ingressproto_ingress_proto_rawDesc), len(file_ingress_ingressproto_ingress_proto_rawDesc)))
	})
	return file_ingress_ingressproto_ingress_proto_rawDescData
}

var file_ingress_ingressproto_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ingress_ingressproto_ingress_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: ingressproto.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 1: ingressproto.AuthorizeResponse
}
var file_ingress_ingressproto_ingress_proto_depIdxs = []int32{
	0, // 0: ingressproto.IngressService.Authorize:input_type -> ingressproto.AuthorizeRequest
	1, // 1: ingressproto.IngressService.Authorize:output_type -> ingressproto.AuthorizeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingress_ingressproto_ingress_proto_init() }
func file_ingress_ingressproto_ingress_proto_init() {
	if File_ingress_ingressproto_ingress_proto != nil {
		return
	}
	file_ingress_ingressproto_ingress_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingress_ingressproto_ingress_proto_rawDesc), len(file_ingress_ingressproto_ingress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingress_ingressproto_ingress_proto_goTypes,
		DependencyIndexes: file_ingress_ingressproto_ingress_proto_depIdxs,
		MessageInfos:      file_ingress_ingressproto_ingress_proto_msgTypes,
	}.Build()
	File_ingress_ingressproto_ingress_proto = out.File
	file_ingress_ingressproto_ingress_proto_goTypes = nil
	file_ingress_ingressproto_ingress_proto_depIdxs = nil
}
