syntax = "proto3";

import "google/protobuf/empty.proto";

package grpc;
option go_package = "github.com/TexHik620953/liberator-node-go/pkg/api/grpc;grpc";

service FirewallService {
  rpc AddRule(PortRule) returns (AddRuleResponse);
  rpc ListPeerRules(ListPeerRulesRequest) returns (ListRulesResponse);
  rpc RemoveRule(RemoveRuleRequest) returns (google.protobuf.Empty);
  rpc RemoveAllPeerRules(RemoveAllPeerRulesRequest) returns (google.protobuf.Empty);
}


message ListPeerRulesRequest {
  uint64 peer_id = 1;  
}

message ListRulesResponse { 
  repeated PortRule rules = 1;
}

message PortRule {
  uint64 peer_id = 1;
  optional uint32 target_address = 2;
  string protocol = 3;
  uint32 port_range_start = 4;
  optional uint32 port_range_end = 5;
}

message AddRuleResponse {
  uint64 rule_id = 1;
}

message RemoveRuleRequest {
  uint64 rule_id = 1;
}

message RemoveAllPeerRulesRequest {
  uint64 peer_id = 1;
}