// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libusers.sql

package repos

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserById = `-- name: GetUserById :one
select id, created_at, login from libusers where id = $1 limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (Libuser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i Libuser
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Login)
	return i, err
}

const insertUserPortRule = `-- name: InsertUserPortRule :exec
insert into user_ports (user1, target_user, protocol, port_start, port_end) values ($1,$2,$3,$4,$5)
`

type InsertUserPortRuleParams struct {
	User1      *uuid.UUID
	TargetUser *uuid.UUID
	Protocol   string
	PortStart  int32
	PortEnd    pgtype.Int4
}

func (q *Queries) InsertUserPortRule(ctx context.Context, arg InsertUserPortRuleParams) error {
	_, err := q.db.Exec(ctx, insertUserPortRule,
		arg.User1,
		arg.TargetUser,
		arg.Protocol,
		arg.PortStart,
		arg.PortEnd,
	)
	return err
}

const listUserPortsRules = `-- name: ListUserPortsRules :many
select id, created_at, user1, target_user, protocol, port_start, port_end from user_ports where user1 = $1
`

func (q *Queries) ListUserPortsRules(ctx context.Context, user1 *uuid.UUID) ([]UserPort, error) {
	rows, err := q.db.Query(ctx, listUserPortsRules, user1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPort
	for rows.Next() {
		var i UserPort
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.User1,
			&i.TargetUser,
			&i.Protocol,
			&i.PortStart,
			&i.PortEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select id, created_at, login from libusers
`

func (q *Queries) ListUsers(ctx context.Context) ([]Libuser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Libuser
	for rows.Next() {
		var i Libuser
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Login); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
