// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libusers.sql

package repos

import (
	"context"

	"github.com/google/uuid"
)

const getUserById = `-- name: GetUserById :one
select id, login from libusers where id = $1 limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (Libuser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i Libuser
	err := row.Scan(&i.ID, &i.Login)
	return i, err
}

const listUserRules = `-- name: ListUserRules :many
select id, login from libusers where user = $1
`

func (q *Queries) ListUserRules(ctx context.Context, dollar_1 interface{}) ([]Libuser, error) {
	rows, err := q.db.Query(ctx, listUserRules, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Libuser
	for rows.Next() {
		var i Libuser
		if err := rows.Scan(&i.ID, &i.Login); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
