// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repos

import (
	"github.com/google/uuid"
)

type Libuser struct {
	ID    uuid.UUID
	Login string
}

type UserRulesTable struct {
	ID    int64
	User  *uuid.UUID
	Type  string
	Value string
}
