// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repos

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Libuser struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	Login     string
}

type UserPort struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	User1      *uuid.UUID
	TargetUser *uuid.UUID
	Protocol   string
	PortStart  int32
	PortEnd    pgtype.Int4
}
