// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repos

import (
	"database/sql"
	"time"
)

type Peer struct {
	ID             int64
	Type           string
	VirtualIp      int64
	LastSeen       time.Time
	ExpirationDate *time.Time
	FromPeerTotal  int64
	ToPeerTotal    int64
	TrafficLimitGb sql.NullFloat64
	SpeedLimitMbps sql.NullFloat64
	AwgPrivateKey  string
	AwgPublicKey   string
}

type PeersRule struct {
	ID             int64
	PeerID         int64
	TargetIp       *uint32
	Protocol       string
	PortRangeStart int64
	PortRangeEnd   *uint16
}
