// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peers.sql

package repos

import (
	"context"
	"database/sql"
	"time"
)

const createPeerAutoID = `-- name: CreatePeerAutoID :one
INSERT INTO peers (
    type,
    virtual_ip,
    expiration_date,
    traffic_limit_gb,
    speed_limit_mbps,
    awg_private_key,
    awg_public_key
) VALUES (
    ?1,
    COALESCE(
        (SELECT MAX(innerp.virtual_ip) + 1 FROM peers as innerp WHERE innerp.virtual_ip >= ?2),
        ?2
    ),
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
RETURNING id, type, virtual_ip, last_seen, expiration_date, from_peer_total, to_peer_total, traffic_limit_gb, speed_limit_mbps, awg_private_key, awg_public_key
`

type CreatePeerAutoIDParams struct {
	Type           string
	MinVirtualIp   int64
	ExpirationDate *time.Time
	TrafficLimitGb sql.NullFloat64
	SpeedLimitMbps sql.NullFloat64
	AwgPrivateKey  string
	AwgPublicKey   string
}

func (q *Queries) CreatePeerAutoID(ctx context.Context, arg CreatePeerAutoIDParams) (Peer, error) {
	row := q.db.QueryRowContext(ctx, createPeerAutoID,
		arg.Type,
		arg.MinVirtualIp,
		arg.ExpirationDate,
		arg.TrafficLimitGb,
		arg.SpeedLimitMbps,
		arg.AwgPrivateKey,
		arg.AwgPublicKey,
	)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.VirtualIp,
		&i.LastSeen,
		&i.ExpirationDate,
		&i.FromPeerTotal,
		&i.ToPeerTotal,
		&i.TrafficLimitGb,
		&i.SpeedLimitMbps,
		&i.AwgPrivateKey,
		&i.AwgPublicKey,
	)
	return i, err
}

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM peers WHERE id = ?1
`

func (q *Queries) DeletePeer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeer, id)
	return err
}

const getPeerByID = `-- name: GetPeerByID :one
SELECT id, type, virtual_ip, last_seen, expiration_date, from_peer_total, to_peer_total, traffic_limit_gb, speed_limit_mbps, awg_private_key, awg_public_key FROM peers WHERE id = ?1
`

func (q *Queries) GetPeerByID(ctx context.Context, id int64) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByID, id)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.VirtualIp,
		&i.LastSeen,
		&i.ExpirationDate,
		&i.FromPeerTotal,
		&i.ToPeerTotal,
		&i.TrafficLimitGb,
		&i.SpeedLimitMbps,
		&i.AwgPrivateKey,
		&i.AwgPublicKey,
	)
	return i, err
}

const getPeerByVirtualIP = `-- name: GetPeerByVirtualIP :one
SELECT id, type, virtual_ip, last_seen, expiration_date, from_peer_total, to_peer_total, traffic_limit_gb, speed_limit_mbps, awg_private_key, awg_public_key FROM peers WHERE virtual_ip = ?1
`

func (q *Queries) GetPeerByVirtualIP(ctx context.Context, virtualIp int64) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByVirtualIP, virtualIp)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.VirtualIp,
		&i.LastSeen,
		&i.ExpirationDate,
		&i.FromPeerTotal,
		&i.ToPeerTotal,
		&i.TrafficLimitGb,
		&i.SpeedLimitMbps,
		&i.AwgPrivateKey,
		&i.AwgPublicKey,
	)
	return i, err
}

const listPeers = `-- name: ListPeers :many
SELECT id, type, virtual_ip, last_seen, expiration_date, from_peer_total, to_peer_total, traffic_limit_gb, speed_limit_mbps, awg_private_key, awg_public_key FROM peers ORDER BY id
`

func (q *Queries) ListPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, listPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.VirtualIp,
			&i.LastSeen,
			&i.ExpirationDate,
			&i.FromPeerTotal,
			&i.ToPeerTotal,
			&i.TrafficLimitGb,
			&i.SpeedLimitMbps,
			&i.AwgPrivateKey,
			&i.AwgPublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeerStats = `-- name: UpdatePeerStats :exec
UPDATE peers
SET
    from_peer_total = from_peer_total + ?1,
    to_peer_total   = to_peer_total + ?2,
    last_seen       = MAX(last_seen, ?3)
WHERE virtual_ip = ?4
`

type UpdatePeerStatsParams struct {
	FromInc   int64
	ToInc     int64
	LastSeen  interface{}
	VirtualIp int64
}

func (q *Queries) UpdatePeerStats(ctx context.Context, arg UpdatePeerStatsParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerStats,
		arg.FromInc,
		arg.ToInc,
		arg.LastSeen,
		arg.VirtualIp,
	)
	return err
}
