// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package repos

import (
	"context"
)

const deleteAllPeerRules = `-- name: DeleteAllPeerRules :exec
DELETE FROM peers_rules WHERE peer_id = ?
`

func (q *Queries) DeleteAllPeerRules(ctx context.Context, peerID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllPeerRules, peerID)
	return err
}

const deletePeerRule = `-- name: DeletePeerRule :exec
DELETE FROM peers_rules WHERE id = ?
`

func (q *Queries) DeletePeerRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeerRule, id)
	return err
}

const insertPeerRule = `-- name: InsertPeerRule :one
INSERT INTO peers_rules (
    peer_id, target_ip, protocol, port_range_start, port_range_end
) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertPeerRuleParams struct {
	PeerID         int64
	TargetIp       *uint32
	Protocol       string
	PortRangeStart int64
	PortRangeEnd   *uint16
}

func (q *Queries) InsertPeerRule(ctx context.Context, arg InsertPeerRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPeerRule,
		arg.PeerID,
		arg.TargetIp,
		arg.Protocol,
		arg.PortRangeStart,
		arg.PortRangeEnd,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const loadAllRules = `-- name: LoadAllRules :many
SELECT 
    pr.id,
    pr.peer_id,
    p.virtual_ip,
    pr.target_ip,
    pr.protocol,
    pr.port_range_start,
    pr.port_range_end
FROM peers_rules pr
JOIN peers p ON pr.peer_id = p.id
`

type LoadAllRulesRow struct {
	ID             int64
	PeerID         int64
	VirtualIp      int64
	TargetIp       *uint32
	Protocol       string
	PortRangeStart int64
	PortRangeEnd   *uint16
}

func (q *Queries) LoadAllRules(ctx context.Context) ([]LoadAllRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, loadAllRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadAllRulesRow
	for rows.Next() {
		var i LoadAllRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.PeerID,
			&i.VirtualIp,
			&i.TargetIp,
			&i.Protocol,
			&i.PortRangeStart,
			&i.PortRangeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRulesByPeerID = `-- name: LoadRulesByPeerID :many
SELECT
    id,
    peer_id,
    target_ip,
    protocol,
    port_range_start,
    port_range_end
FROM peers_rules
WHERE peer_id = ?1
ORDER BY id
`

func (q *Queries) LoadRulesByPeerID(ctx context.Context, peerID int64) ([]PeersRule, error) {
	rows, err := q.db.QueryContext(ctx, loadRulesByPeerID, peerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeersRule
	for rows.Next() {
		var i PeersRule
		if err := rows.Scan(
			&i.ID,
			&i.PeerID,
			&i.TargetIp,
			&i.Protocol,
			&i.PortRangeStart,
			&i.PortRangeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
