// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/mesh/services/meshrouting/proto/meshrouting.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshRoutingService_PushConnectionUpdate_FullMethodName = "/proto.MeshRoutingService/PushConnectionUpdate"
	MeshRoutingService_PullFullTable_FullMethodName        = "/proto.MeshRoutingService/PullFullTable"
)

// MeshRoutingServiceClient is the client API for MeshRoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeshRoutingServiceClient interface {
	PushConnectionUpdate(ctx context.Context, in *UserConnectionUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PullFullTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersConnectionsList, error)
}

type meshRoutingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshRoutingServiceClient(cc grpc.ClientConnInterface) MeshRoutingServiceClient {
	return &meshRoutingServiceClient{cc}
}

func (c *meshRoutingServiceClient) PushConnectionUpdate(ctx context.Context, in *UserConnectionUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MeshRoutingService_PushConnectionUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshRoutingServiceClient) PullFullTable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersConnectionsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersConnectionsList)
	err := c.cc.Invoke(ctx, MeshRoutingService_PullFullTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshRoutingServiceServer is the server API for MeshRoutingService service.
// All implementations must embed UnimplementedMeshRoutingServiceServer
// for forward compatibility.
type MeshRoutingServiceServer interface {
	PushConnectionUpdate(context.Context, *UserConnectionUpdate) (*emptypb.Empty, error)
	PullFullTable(context.Context, *emptypb.Empty) (*UsersConnectionsList, error)
	mustEmbedUnimplementedMeshRoutingServiceServer()
}

// UnimplementedMeshRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshRoutingServiceServer struct{}

func (UnimplementedMeshRoutingServiceServer) PushConnectionUpdate(context.Context, *UserConnectionUpdate) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PushConnectionUpdate not implemented")
}
func (UnimplementedMeshRoutingServiceServer) PullFullTable(context.Context, *emptypb.Empty) (*UsersConnectionsList, error) {
	return nil, status.Error(codes.Unimplemented, "method PullFullTable not implemented")
}
func (UnimplementedMeshRoutingServiceServer) mustEmbedUnimplementedMeshRoutingServiceServer() {}
func (UnimplementedMeshRoutingServiceServer) testEmbeddedByValue()                            {}

// UnsafeMeshRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshRoutingServiceServer will
// result in compilation errors.
type UnsafeMeshRoutingServiceServer interface {
	mustEmbedUnimplementedMeshRoutingServiceServer()
}

func RegisterMeshRoutingServiceServer(s grpc.ServiceRegistrar, srv MeshRoutingServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshRoutingService_ServiceDesc, srv)
}

func _MeshRoutingService_PushConnectionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConnectionUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshRoutingServiceServer).PushConnectionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshRoutingService_PushConnectionUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshRoutingServiceServer).PushConnectionUpdate(ctx, req.(*UserConnectionUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshRoutingService_PullFullTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshRoutingServiceServer).PullFullTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshRoutingService_PullFullTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshRoutingServiceServer).PullFullTable(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshRoutingService_ServiceDesc is the grpc.ServiceDesc for MeshRoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshRoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MeshRoutingService",
	HandlerType: (*MeshRoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushConnectionUpdate",
			Handler:    _MeshRoutingService_PushConnectionUpdate_Handler,
		},
		{
			MethodName: "PullFullTable",
			Handler:    _MeshRoutingService_PullFullTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/mesh/services/meshrouting/proto/meshrouting.proto",
}
