// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/services/meshrouting/proto/meshrouting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_ADD    UpdateType = 0
	UpdateType_REMOVE UpdateType = 1
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	UpdateType_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{0}
}

type PortRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUser     *string                `protobuf:"bytes,1,opt,name=target_user,json=targetUser,proto3,oneof" json:"target_user,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PortRangeStart uint32                 `protobuf:"varint,3,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd   *uint32                `protobuf:"varint,4,opt,name=port_range_end,json=portRangeEnd,proto3,oneof" json:"port_range_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PortRule) Reset() {
	*x = PortRule{}
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRule) ProtoMessage() {}

func (x *PortRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRule.ProtoReflect.Descriptor instead.
func (*PortRule) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{0}
}

func (x *PortRule) GetTargetUser() string {
	if x != nil && x.TargetUser != nil {
		return *x.TargetUser
	}
	return ""
}

func (x *PortRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortRule) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *PortRule) GetPortRangeEnd() uint32 {
	if x != nil && x.PortRangeEnd != nil {
		return *x.PortRangeEnd
	}
	return 0
}

type UserConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Rules         []*PortRule            `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{1}
}

func (x *UserConnection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserConnection) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *UserConnection) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UserConnection) GetRules() []*PortRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UserConnectionUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=proto.UpdateType" json:"type,omitempty"`
	Add             *UserConnection        `protobuf:"bytes,2,opt,name=add,proto3" json:"add,omitempty"`
	RemoveVirtualIp string                 `protobuf:"bytes,3,opt,name=remove_virtual_ip,json=removeVirtualIp,proto3" json:"remove_virtual_ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserConnectionUpdate) Reset() {
	*x = UserConnectionUpdate{}
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnectionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnectionUpdate) ProtoMessage() {}

func (x *UserConnectionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnectionUpdate.ProtoReflect.Descriptor instead.
func (*UserConnectionUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{2}
}

func (x *UserConnectionUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_ADD
}

func (x *UserConnectionUpdate) GetAdd() *UserConnection {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UserConnectionUpdate) GetRemoveVirtualIp() string {
	if x != nil {
		return x.RemoveVirtualIp
	}
	return ""
}

type UsersConnectionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*UserConnection      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersConnectionsList) Reset() {
	*x = UsersConnectionsList{}
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersConnectionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersConnectionsList) ProtoMessage() {}

func (x *UsersConnectionsList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersConnectionsList.ProtoReflect.Descriptor instead.
func (*UsersConnectionsList) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP(), []int{3}
}

func (x *UsersConnectionsList) GetConnections() []*UserConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_pkg_mesh_services_meshrouting_proto_meshrouting_proto protoreflect.FileDescriptor

const file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDesc = "" +
	"\n" +
	"5pkg/mesh/services/meshrouting/proto/meshrouting.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc4\x01\n" +
	"\bPortRule\x12$\n" +
	"\vtarget_user\x18\x01 \x01(\tH\x00R\n" +
	"targetUser\x88\x01\x01\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12(\n" +
	"\x10port_range_start\x18\x03 \x01(\rR\x0eportRangeStart\x12)\n" +
	"\x0eport_range_end\x18\x04 \x01(\rH\x01R\fportRangeEnd\x88\x01\x01B\x0e\n" +
	"\f_target_userB\x11\n" +
	"\x0f_port_range_end\"\x88\x01\n" +
	"\x0eUserConnection\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12%\n" +
	"\x05rules\x18\x04 \x03(\v2\x0f.proto.PortRuleR\x05rules\"\x92\x01\n" +
	"\x14UserConnectionUpdate\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.proto.UpdateTypeR\x04type\x12'\n" +
	"\x03add\x18\x02 \x01(\v2\x15.proto.UserConnectionR\x03add\x12*\n" +
	"\x11remove_virtual_ip\x18\x03 \x01(\tR\x0fremoveVirtualIp\"O\n" +
	"\x14UsersConnectionsList\x127\n" +
	"\vconnections\x18\x01 \x03(\v2\x15.proto.UserConnectionR\vconnections*!\n" +
	"\n" +
	"UpdateType\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x012\xa7\x01\n" +
	"\x12MeshRoutingService\x12K\n" +
	"\x14PushConnectionUpdate\x12\x1b.proto.UserConnectionUpdate\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rPullFullTable\x12\x16.google.protobuf.Empty\x1a\x1b.proto.UsersConnectionsListB\tZ\a./protob\x06proto3"

var (
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescOnce sync.Once
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescData []byte
)

func file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescGZIP() []byte {
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDesc), len(file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDesc)))
	})
	return file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDescData
}

var file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_goTypes = []any{
	(UpdateType)(0),              // 0: proto.UpdateType
	(*PortRule)(nil),             // 1: proto.PortRule
	(*UserConnection)(nil),       // 2: proto.UserConnection
	(*UserConnectionUpdate)(nil), // 3: proto.UserConnectionUpdate
	(*UsersConnectionsList)(nil), // 4: proto.UsersConnectionsList
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_depIdxs = []int32{
	1, // 0: proto.UserConnection.rules:type_name -> proto.PortRule
	0, // 1: proto.UserConnectionUpdate.type:type_name -> proto.UpdateType
	2, // 2: proto.UserConnectionUpdate.add:type_name -> proto.UserConnection
	2, // 3: proto.UsersConnectionsList.connections:type_name -> proto.UserConnection
	3, // 4: proto.MeshRoutingService.PushConnectionUpdate:input_type -> proto.UserConnectionUpdate
	5, // 5: proto.MeshRoutingService.PullFullTable:input_type -> google.protobuf.Empty
	5, // 6: proto.MeshRoutingService.PushConnectionUpdate:output_type -> google.protobuf.Empty
	4, // 7: proto.MeshRoutingService.PullFullTable:output_type -> proto.UsersConnectionsList
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_init() }
func file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_init() {
	if File_pkg_mesh_services_meshrouting_proto_meshrouting_proto != nil {
		return
	}
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDesc), len(file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_depIdxs,
		EnumInfos:         file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_enumTypes,
		MessageInfos:      file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_msgTypes,
	}.Build()
	File_pkg_mesh_services_meshrouting_proto_meshrouting_proto = out.File
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_goTypes = nil
	file_pkg_mesh_services_meshrouting_proto_meshrouting_proto_depIdxs = nil
}
