syntax = "proto3";
package proto;
option go_package = "./proto";

import "google/protobuf/empty.proto";

//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pkg/mesh/services/discovery/proto/discovery.proto

message PeerInfo {
    string id = 1;
    string addr = 2;
    int64 last_seen = 3;
};
message ListKnownPeersResponse {
  repeated PeerInfo peers = 1;
};



service DiscoveryService {
    rpc PullKnownPeers(google.protobuf.Empty) returns(ListKnownPeersResponse);
}

