// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/services/discovery/proto/discovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type ListKnownPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownPeersResponse) Reset() {
	*x = ListKnownPeersResponse{}
	mi := &file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownPeersResponse) ProtoMessage() {}

func (x *ListKnownPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownPeersResponse.ProtoReflect.Descriptor instead.
func (*ListKnownPeersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ListKnownPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_pkg_mesh_services_discovery_proto_discovery_proto protoreflect.FileDescriptor

const file_pkg_mesh_services_discovery_proto_discovery_proto_rawDesc = "" +
	"\n" +
	"1pkg/mesh/services/discovery/proto/discovery.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"K\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"?\n" +
	"\x16ListKnownPeersResponse\x12%\n" +
	"\x05peers\x18\x01 \x03(\v2\x0f.proto.PeerInfoR\x05peers2[\n" +
	"\x10DiscoveryService\x12G\n" +
	"\x0ePullKnownPeers\x12\x16.google.protobuf.Empty\x1a\x1d.proto.ListKnownPeersResponseB\tZ\a./protob\x06proto3"

var (
	file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescOnce sync.Once
	file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescData []byte
)

func file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescGZIP() []byte {
	file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_services_discovery_proto_discovery_proto_rawDesc), len(file_pkg_mesh_services_discovery_proto_discovery_proto_rawDesc)))
	})
	return file_pkg_mesh_services_discovery_proto_discovery_proto_rawDescData
}

var file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_mesh_services_discovery_proto_discovery_proto_goTypes = []any{
	(*PeerInfo)(nil),               // 0: proto.PeerInfo
	(*ListKnownPeersResponse)(nil), // 1: proto.ListKnownPeersResponse
	(*emptypb.Empty)(nil),          // 2: google.protobuf.Empty
}
var file_pkg_mesh_services_discovery_proto_discovery_proto_depIdxs = []int32{
	0, // 0: proto.ListKnownPeersResponse.peers:type_name -> proto.PeerInfo
	2, // 1: proto.DiscoveryService.PullKnownPeers:input_type -> google.protobuf.Empty
	1, // 2: proto.DiscoveryService.PullKnownPeers:output_type -> proto.ListKnownPeersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_mesh_services_discovery_proto_discovery_proto_init() }
func file_pkg_mesh_services_discovery_proto_discovery_proto_init() {
	if File_pkg_mesh_services_discovery_proto_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_services_discovery_proto_discovery_proto_rawDesc), len(file_pkg_mesh_services_discovery_proto_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_services_discovery_proto_discovery_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_services_discovery_proto_discovery_proto_depIdxs,
		MessageInfos:      file_pkg_mesh_services_discovery_proto_discovery_proto_msgTypes,
	}.Build()
	File_pkg_mesh_services_discovery_proto_discovery_proto = out.File
	file_pkg_mesh_services_discovery_proto_discovery_proto_goTypes = nil
	file_pkg_mesh_services_discovery_proto_discovery_proto_depIdxs = nil
}
