syntax = "proto3";
package proto;
option go_package = "./proto";

import "google/protobuf/empty.proto";

//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative mesh/discovery/proto/discovery.proto

message IpInfo {
    string country = 1;
    string country_code = 2;
    string region = 3;
    string region_name = 4;
    string city = 5;
    string zip = 6;
    double lat = 7;
    double lon = 8;
    string timezone = 9;
    string isp = 10;
    string org = 11;
    string as = 12;
    string query = 13;
};

message PeerInfo {
    string id = 1;
    map<string,bool> addr = 2;
    int64 last_seen = 3;
    optional IpInfo ip_info = 4;
};
message ListKnownPeersResponse {
  repeated PeerInfo peers = 1;
};


message RttMap {
    map<string,int64> rttMap = 1;
};
message RttUpdateRequest {
    map<string, RttMap> rttMap = 1;
};


service DiscoveryService {
    // List all peers known by node.
    rpc PullKnownPeers(google.protobuf.Empty) returns(ListKnownPeersResponse);
    
    //rpc NotifyRTT(RttUpdateRequest) returns(google.protobuf.Empty);
}

