// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/mesh/meshservice/proto/meshservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerEventType int32

const (
	PeerEventType_PEER_EVENT_SYNC    PeerEventType = 0
	PeerEventType_PEER_EVENT_JOINED  PeerEventType = 1 // Новый узел в сети
	PeerEventType_PEER_EVENT_UPDATED PeerEventType = 2 // Узел обновил статус (alive)
	PeerEventType_PEER_EVENT_LEFT    PeerEventType = 3 // Узел отключился
)

// Enum value maps for PeerEventType.
var (
	PeerEventType_name = map[int32]string{
		0: "PEER_EVENT_SYNC",
		1: "PEER_EVENT_JOINED",
		2: "PEER_EVENT_UPDATED",
		3: "PEER_EVENT_LEFT",
	}
	PeerEventType_value = map[string]int32{
		"PEER_EVENT_SYNC":    0,
		"PEER_EVENT_JOINED":  1,
		"PEER_EVENT_UPDATED": 2,
		"PEER_EVENT_LEFT":    3,
	}
)

func (x PeerEventType) Enum() *PeerEventType {
	p := new(PeerEventType)
	*p = x
	return p
}

func (x PeerEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mesh_meshservice_proto_meshservice_proto_enumTypes[0].Descriptor()
}

func (PeerEventType) Type() protoreflect.EnumType {
	return &file_pkg_mesh_meshservice_proto_meshservice_proto_enumTypes[0]
}

func (x PeerEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerEventType.Descriptor instead.
func (PeerEventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescGZIP(), []int{0}
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PeerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerEventType          `protobuf:"varint,1,opt,name=type,proto3,enum=proto.PeerEventType" json:"type,omitempty"`
	Update        *PeerInfo              `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	Dump          []*PeerInfo            `protobuf:"bytes,3,rep,name=dump,proto3" json:"dump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvent) Reset() {
	*x = PeerEvent{}
	mi := &file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvent) ProtoMessage() {}

func (x *PeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvent.ProtoReflect.Descriptor instead.
func (*PeerEvent) Descriptor() ([]byte, []int) {
	return file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescGZIP(), []int{1}
}

func (x *PeerEvent) GetType() PeerEventType {
	if x != nil {
		return x.Type
	}
	return PeerEventType_PEER_EVENT_SYNC
}

func (x *PeerEvent) GetUpdate() *PeerInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PeerEvent) GetDump() []*PeerInfo {
	if x != nil {
		return x.Dump
	}
	return nil
}

var File_pkg_mesh_meshservice_proto_meshservice_proto protoreflect.FileDescriptor

const file_pkg_mesh_meshservice_proto_meshservice_proto_rawDesc = "" +
	"\n" +
	",pkg/mesh/meshservice/proto/meshservice.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"K\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"\x83\x01\n" +
	"\tPeerEvent\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.proto.PeerEventTypeR\x04type\x12'\n" +
	"\x06update\x18\x02 \x01(\v2\x0f.proto.PeerInfoR\x06update\x12#\n" +
	"\x04dump\x18\x03 \x03(\v2\x0f.proto.PeerInfoR\x04dump*h\n" +
	"\rPeerEventType\x12\x13\n" +
	"\x0fPEER_EVENT_SYNC\x10\x00\x12\x15\n" +
	"\x11PEER_EVENT_JOINED\x10\x01\x12\x16\n" +
	"\x12PEER_EVENT_UPDATED\x10\x02\x12\x13\n" +
	"\x0fPEER_EVENT_LEFT\x10\x032P\n" +
	"\x10DiscoveryService\x12<\n" +
	"\x0eSubscribePeers\x12\x16.google.protobuf.Empty\x1a\x10.proto.PeerEvent0\x01B\tZ\a./protob\x06proto3"

var (
	file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescOnce sync.Once
	file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescData []byte
)

func file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescGZIP() []byte {
	file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescOnce.Do(func() {
		file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mesh_meshservice_proto_meshservice_proto_rawDesc), len(file_pkg_mesh_meshservice_proto_meshservice_proto_rawDesc)))
	})
	return file_pkg_mesh_meshservice_proto_meshservice_proto_rawDescData
}

var file_pkg_mesh_meshservice_proto_meshservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_mesh_meshservice_proto_meshservice_proto_goTypes = []any{
	(PeerEventType)(0),    // 0: proto.PeerEventType
	(*PeerInfo)(nil),      // 1: proto.PeerInfo
	(*PeerEvent)(nil),     // 2: proto.PeerEvent
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_pkg_mesh_meshservice_proto_meshservice_proto_depIdxs = []int32{
	0, // 0: proto.PeerEvent.type:type_name -> proto.PeerEventType
	1, // 1: proto.PeerEvent.update:type_name -> proto.PeerInfo
	1, // 2: proto.PeerEvent.dump:type_name -> proto.PeerInfo
	3, // 3: proto.DiscoveryService.SubscribePeers:input_type -> google.protobuf.Empty
	2, // 4: proto.DiscoveryService.SubscribePeers:output_type -> proto.PeerEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_mesh_meshservice_proto_meshservice_proto_init() }
func file_pkg_mesh_meshservice_proto_meshservice_proto_init() {
	if File_pkg_mesh_meshservice_proto_meshservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mesh_meshservice_proto_meshservice_proto_rawDesc), len(file_pkg_mesh_meshservice_proto_meshservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mesh_meshservice_proto_meshservice_proto_goTypes,
		DependencyIndexes: file_pkg_mesh_meshservice_proto_meshservice_proto_depIdxs,
		EnumInfos:         file_pkg_mesh_meshservice_proto_meshservice_proto_enumTypes,
		MessageInfos:      file_pkg_mesh_meshservice_proto_meshservice_proto_msgTypes,
	}.Build()
	File_pkg_mesh_meshservice_proto_meshservice_proto = out.File
	file_pkg_mesh_meshservice_proto_meshservice_proto_goTypes = nil
	file_pkg_mesh_meshservice_proto_meshservice_proto_depIdxs = nil
}
