// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: firewall.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetAddress  *uint32                `protobuf:"varint,1,opt,name=target_address,json=targetAddress,proto3,oneof" json:"target_address,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PortRangeStart uint32                 `protobuf:"varint,3,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd   *uint32                `protobuf:"varint,4,opt,name=port_range_end,json=portRangeEnd,proto3,oneof" json:"port_range_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PortRule) Reset() {
	*x = PortRule{}
	mi := &file_firewall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRule) ProtoMessage() {}

func (x *PortRule) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRule.ProtoReflect.Descriptor instead.
func (*PortRule) Descriptor() ([]byte, []int) {
	return file_firewall_proto_rawDescGZIP(), []int{0}
}

func (x *PortRule) GetTargetAddress() uint32 {
	if x != nil && x.TargetAddress != nil {
		return *x.TargetAddress
	}
	return 0
}

func (x *PortRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortRule) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *PortRule) GetPortRangeEnd() uint32 {
	if x != nil && x.PortRangeEnd != nil {
		return *x.PortRangeEnd
	}
	return 0
}

type AddRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        uint64                 `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Rule          *PortRule              `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleRequest) Reset() {
	*x = AddRuleRequest{}
	mi := &file_firewall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleRequest) ProtoMessage() {}

func (x *AddRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRuleRequest) Descriptor() ([]byte, []int) {
	return file_firewall_proto_rawDescGZIP(), []int{1}
}

func (x *AddRuleRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *AddRuleRequest) GetRule() *PortRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint64                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleResponse) Reset() {
	*x = AddRuleResponse{}
	mi := &file_firewall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleResponse) ProtoMessage() {}

func (x *AddRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleResponse.ProtoReflect.Descriptor instead.
func (*AddRuleResponse) Descriptor() ([]byte, []int) {
	return file_firewall_proto_rawDescGZIP(), []int{2}
}

func (x *AddRuleResponse) GetRuleId() uint64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type RemoveRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint64                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleRequest) Reset() {
	*x = RemoveRuleRequest{}
	mi := &file_firewall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleRequest) ProtoMessage() {}

func (x *RemoveRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRuleRequest) Descriptor() ([]byte, []int) {
	return file_firewall_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveRuleRequest) GetRuleId() uint64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type RemoveAllPeerRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        uint64                 `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllPeerRulesRequest) Reset() {
	*x = RemoveAllPeerRulesRequest{}
	mi := &file_firewall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllPeerRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllPeerRulesRequest) ProtoMessage() {}

func (x *RemoveAllPeerRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllPeerRulesRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllPeerRulesRequest) Descriptor() ([]byte, []int) {
	return file_firewall_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveAllPeerRulesRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

var File_firewall_proto protoreflect.FileDescriptor

const file_firewall_proto_rawDesc = "" +
	"\n" +
	"\x0efirewall.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\bPortRule\x12*\n" +
	"\x0etarget_address\x18\x01 \x01(\rH\x00R\rtargetAddress\x88\x01\x01\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12(\n" +
	"\x10port_range_start\x18\x03 \x01(\rR\x0eportRangeStart\x12)\n" +
	"\x0eport_range_end\x18\x04 \x01(\rH\x01R\fportRangeEnd\x88\x01\x01B\x11\n" +
	"\x0f_target_addressB\x11\n" +
	"\x0f_port_range_end\"M\n" +
	"\x0eAddRuleRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x04R\x06peerId\x12\"\n" +
	"\x04rule\x18\x02 \x01(\v2\x0e.grpc.PortRuleR\x04rule\"*\n" +
	"\x0fAddRuleResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x04R\x06ruleId\",\n" +
	"\x11RemoveRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x04R\x06ruleId\"4\n" +
	"\x19RemoveAllPeerRulesRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x04R\x06peerId2\xd7\x01\n" +
	"\x0fFirewallService\x126\n" +
	"\aAddRule\x12\x14.grpc.AddRuleRequest\x1a\x15.grpc.AddRuleResponse\x12=\n" +
	"\n" +
	"RemoveRule\x12\x17.grpc.RemoveRuleRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x12RemoveAllPeerRules\x12\x1f.grpc.RemoveAllPeerRulesRequest\x1a\x16.google.protobuf.EmptyB=Z;github.com/TexHik620953/liberator-node-go/pkg/api/grpc;grpcb\x06proto3"

var (
	file_firewall_proto_rawDescOnce sync.Once
	file_firewall_proto_rawDescData []byte
)

func file_firewall_proto_rawDescGZIP() []byte {
	file_firewall_proto_rawDescOnce.Do(func() {
		file_firewall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_firewall_proto_rawDesc), len(file_firewall_proto_rawDesc)))
	})
	return file_firewall_proto_rawDescData
}

var file_firewall_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_firewall_proto_goTypes = []any{
	(*PortRule)(nil),                  // 0: grpc.PortRule
	(*AddRuleRequest)(nil),            // 1: grpc.AddRuleRequest
	(*AddRuleResponse)(nil),           // 2: grpc.AddRuleResponse
	(*RemoveRuleRequest)(nil),         // 3: grpc.RemoveRuleRequest
	(*RemoveAllPeerRulesRequest)(nil), // 4: grpc.RemoveAllPeerRulesRequest
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_firewall_proto_depIdxs = []int32{
	0, // 0: grpc.AddRuleRequest.rule:type_name -> grpc.PortRule
	1, // 1: grpc.FirewallService.AddRule:input_type -> grpc.AddRuleRequest
	3, // 2: grpc.FirewallService.RemoveRule:input_type -> grpc.RemoveRuleRequest
	4, // 3: grpc.FirewallService.RemoveAllPeerRules:input_type -> grpc.RemoveAllPeerRulesRequest
	2, // 4: grpc.FirewallService.AddRule:output_type -> grpc.AddRuleResponse
	5, // 5: grpc.FirewallService.RemoveRule:output_type -> google.protobuf.Empty
	5, // 6: grpc.FirewallService.RemoveAllPeerRules:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_firewall_proto_init() }
func file_firewall_proto_init() {
	if File_firewall_proto != nil {
		return
	}
	file_firewall_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_firewall_proto_rawDesc), len(file_firewall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_firewall_proto_goTypes,
		DependencyIndexes: file_firewall_proto_depIdxs,
		MessageInfos:      file_firewall_proto_msgTypes,
	}.Build()
	File_firewall_proto = out.File
	file_firewall_proto_goTypes = nil
	file_firewall_proto_depIdxs = nil
}
