// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: firewall.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FirewallService_AddRule_FullMethodName            = "/grpc.FirewallService/AddRule"
	FirewallService_ListPeerRules_FullMethodName      = "/grpc.FirewallService/ListPeerRules"
	FirewallService_RemoveRule_FullMethodName         = "/grpc.FirewallService/RemoveRule"
	FirewallService_RemoveAllPeerRules_FullMethodName = "/grpc.FirewallService/RemoveAllPeerRules"
)

// FirewallServiceClient is the client API for FirewallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirewallServiceClient interface {
	AddRule(ctx context.Context, in *PortRule, opts ...grpc.CallOption) (*AddRuleResponse, error)
	ListPeerRules(ctx context.Context, in *ListPeerRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveAllPeerRules(ctx context.Context, in *RemoveAllPeerRulesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type firewallServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewallServiceClient(cc grpc.ClientConnInterface) FirewallServiceClient {
	return &firewallServiceClient{cc}
}

func (c *firewallServiceClient) AddRule(ctx context.Context, in *PortRule, opts ...grpc.CallOption) (*AddRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRuleResponse)
	err := c.cc.Invoke(ctx, FirewallService_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) ListPeerRules(ctx context.Context, in *ListPeerRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, FirewallService_ListPeerRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FirewallService_RemoveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) RemoveAllPeerRules(ctx context.Context, in *RemoveAllPeerRulesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FirewallService_RemoveAllPeerRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewallServiceServer is the server API for FirewallService service.
// All implementations must embed UnimplementedFirewallServiceServer
// for forward compatibility.
type FirewallServiceServer interface {
	AddRule(context.Context, *PortRule) (*AddRuleResponse, error)
	ListPeerRules(context.Context, *ListPeerRulesRequest) (*ListRulesResponse, error)
	RemoveRule(context.Context, *RemoveRuleRequest) (*emptypb.Empty, error)
	RemoveAllPeerRules(context.Context, *RemoveAllPeerRulesRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFirewallServiceServer()
}

// UnimplementedFirewallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirewallServiceServer struct{}

func (UnimplementedFirewallServiceServer) AddRule(context.Context, *PortRule) (*AddRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedFirewallServiceServer) ListPeerRules(context.Context, *ListPeerRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeerRules not implemented")
}
func (UnimplementedFirewallServiceServer) RemoveRule(context.Context, *RemoveRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRule not implemented")
}
func (UnimplementedFirewallServiceServer) RemoveAllPeerRules(context.Context, *RemoveAllPeerRulesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAllPeerRules not implemented")
}
func (UnimplementedFirewallServiceServer) mustEmbedUnimplementedFirewallServiceServer() {}
func (UnimplementedFirewallServiceServer) testEmbeddedByValue()                         {}

// UnsafeFirewallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewallServiceServer will
// result in compilation errors.
type UnsafeFirewallServiceServer interface {
	mustEmbedUnimplementedFirewallServiceServer()
}

func RegisterFirewallServiceServer(s grpc.ServiceRegistrar, srv FirewallServiceServer) {
	// If the following call panics, it indicates UnimplementedFirewallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirewallService_ServiceDesc, srv)
}

func _FirewallService_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortRule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).AddRule(ctx, req.(*PortRule))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_ListPeerRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeerRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).ListPeerRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_ListPeerRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).ListPeerRules(ctx, req.(*ListPeerRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_RemoveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).RemoveRule(ctx, req.(*RemoveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_RemoveAllPeerRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllPeerRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).RemoveAllPeerRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_RemoveAllPeerRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).RemoveAllPeerRules(ctx, req.(*RemoveAllPeerRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewallService_ServiceDesc is the grpc.ServiceDesc for FirewallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FirewallService",
	HandlerType: (*FirewallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRule",
			Handler:    _FirewallService_AddRule_Handler,
		},
		{
			MethodName: "ListPeerRules",
			Handler:    _FirewallService_ListPeerRules_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _FirewallService_RemoveRule_Handler,
		},
		{
			MethodName: "RemoveAllPeerRules",
			Handler:    _FirewallService_RemoveAllPeerRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firewall.proto",
}
