// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: peers.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProlongPeerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewExpirationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=new_expiration_date,json=newExpirationDate,proto3" json:"new_expiration_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProlongPeerRequest) Reset() {
	*x = ProlongPeerRequest{}
	mi := &file_peers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProlongPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProlongPeerRequest) ProtoMessage() {}

func (x *ProlongPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProlongPeerRequest.ProtoReflect.Descriptor instead.
func (*ProlongPeerRequest) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{0}
}

func (x *ProlongPeerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProlongPeerRequest) GetNewExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpirationDate
	}
	return nil
}

type CreatePeerAutoIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	TrafficLimitGb *float64               `protobuf:"fixed64,3,opt,name=traffic_limit_gb,json=trafficLimitGb,proto3,oneof" json:"traffic_limit_gb,omitempty"`
	SpeedLimitMbps *float64               `protobuf:"fixed64,4,opt,name=speed_limit_mbps,json=speedLimitMbps,proto3,oneof" json:"speed_limit_mbps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePeerAutoIDRequest) Reset() {
	*x = CreatePeerAutoIDRequest{}
	mi := &file_peers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerAutoIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerAutoIDRequest) ProtoMessage() {}

func (x *CreatePeerAutoIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerAutoIDRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerAutoIDRequest) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePeerAutoIDRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePeerAutoIDRequest) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *CreatePeerAutoIDRequest) GetTrafficLimitGb() float64 {
	if x != nil && x.TrafficLimitGb != nil {
		return *x.TrafficLimitGb
	}
	return 0
}

func (x *CreatePeerAutoIDRequest) GetSpeedLimitMbps() float64 {
	if x != nil && x.SpeedLimitMbps != nil {
		return *x.SpeedLimitMbps
	}
	return 0
}

type CreatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VirtualIp     uint32                 `protobuf:"varint,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	AwgPrivateKey string                 `protobuf:"bytes,3,opt,name=awg_private_key,json=awgPrivateKey,proto3" json:"awg_private_key,omitempty"`
	AwgPublicKey  string                 `protobuf:"bytes,4,opt,name=awg_public_key,json=awgPublicKey,proto3" json:"awg_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerResponse) Reset() {
	*x = CreatePeerResponse{}
	mi := &file_peers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerResponse) ProtoMessage() {}

func (x *CreatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerResponse.ProtoReflect.Descriptor instead.
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePeerResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePeerResponse) GetVirtualIp() uint32 {
	if x != nil {
		return x.VirtualIp
	}
	return 0
}

func (x *CreatePeerResponse) GetAwgPrivateKey() string {
	if x != nil {
		return x.AwgPrivateKey
	}
	return ""
}

func (x *CreatePeerResponse) GetAwgPublicKey() string {
	if x != nil {
		return x.AwgPublicKey
	}
	return ""
}

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_peers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Peer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	VirtualIp      uint32                 `protobuf:"varint,3,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	FromPeerTotal  uint64                 `protobuf:"varint,6,opt,name=from_peer_total,json=fromPeerTotal,proto3" json:"from_peer_total,omitempty"`
	ToPeerTotal    uint64                 `protobuf:"varint,7,opt,name=to_peer_total,json=toPeerTotal,proto3" json:"to_peer_total,omitempty"`
	AwgPrivateKey  string                 `protobuf:"bytes,8,opt,name=awg_private_key,json=awgPrivateKey,proto3" json:"awg_private_key,omitempty"`
	AwgPublicKey   string                 `protobuf:"bytes,9,opt,name=awg_public_key,json=awgPublicKey,proto3" json:"awg_public_key,omitempty"`
	TrafficLimitGb *float64               `protobuf:"fixed64,10,opt,name=traffic_limit_gb,json=trafficLimitGb,proto3,oneof" json:"traffic_limit_gb,omitempty"`
	SpeedLimitMbps *float64               `protobuf:"fixed64,11,opt,name=speed_limit_mbps,json=speedLimitMbps,proto3,oneof" json:"speed_limit_mbps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_peers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Peer) GetVirtualIp() uint32 {
	if x != nil {
		return x.VirtualIp
	}
	return 0
}

func (x *Peer) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Peer) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *Peer) GetFromPeerTotal() uint64 {
	if x != nil {
		return x.FromPeerTotal
	}
	return 0
}

func (x *Peer) GetToPeerTotal() uint64 {
	if x != nil {
		return x.ToPeerTotal
	}
	return 0
}

func (x *Peer) GetAwgPrivateKey() string {
	if x != nil {
		return x.AwgPrivateKey
	}
	return ""
}

func (x *Peer) GetAwgPublicKey() string {
	if x != nil {
		return x.AwgPublicKey
	}
	return ""
}

func (x *Peer) GetTrafficLimitGb() float64 {
	if x != nil && x.TrafficLimitGb != nil {
		return *x.TrafficLimitGb
	}
	return 0
}

func (x *Peer) GetSpeedLimitMbps() float64 {
	if x != nil && x.SpeedLimitMbps != nil {
		return *x.SpeedLimitMbps
	}
	return 0
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_peers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type DeletePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerRequest) Reset() {
	*x = DeletePeerRequest{}
	mi := &file_peers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerRequest) ProtoMessage() {}

func (x *DeletePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePeerRequest.ProtoReflect.Descriptor instead.
func (*DeletePeerRequest) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePeerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenerateClientKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        uint64                 `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateClientKeyRequest) Reset() {
	*x = GenerateClientKeyRequest{}
	mi := &file_peers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateClientKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateClientKeyRequest) ProtoMessage() {}

func (x *GenerateClientKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateClientKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateClientKeyRequest) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateClientKeyRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *GenerateClientKeyRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GenerateClientKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenerateClientKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateClientKeyResponse) Reset() {
	*x = GenerateClientKeyResponse{}
	mi := &file_peers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateClientKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateClientKeyResponse) ProtoMessage() {}

func (x *GenerateClientKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateClientKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateClientKeyResponse) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateClientKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_peers_proto protoreflect.FileDescriptor

const file_peers_proto_rawDesc = "" +
	"\n" +
	"\vpeers.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x12ProlongPeerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12J\n" +
	"\x13new_expiration_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11newExpirationDate\"\xfa\x01\n" +
	"\x17CreatePeerAutoIDRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12C\n" +
	"\x0fexpiration_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12-\n" +
	"\x10traffic_limit_gb\x18\x03 \x01(\x01H\x00R\x0etrafficLimitGb\x88\x01\x01\x12-\n" +
	"\x10speed_limit_mbps\x18\x04 \x01(\x01H\x01R\x0espeedLimitMbps\x88\x01\x01B\x13\n" +
	"\x11_traffic_limit_gbB\x13\n" +
	"\x11_speed_limit_mbps\"\x91\x01\n" +
	"\x12CreatePeerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\rR\tvirtualIp\x12&\n" +
	"\x0fawg_private_key\x18\x03 \x01(\tR\rawgPrivateKey\x12$\n" +
	"\x0eawg_public_key\x18\x04 \x01(\tR\fawgPublicKey\" \n" +
	"\x0eGetPeerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xe9\x03\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x03 \x01(\rR\tvirtualIp\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12C\n" +
	"\x0fexpiration_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12&\n" +
	"\x0ffrom_peer_total\x18\x06 \x01(\x04R\rfromPeerTotal\x12\"\n" +
	"\rto_peer_total\x18\a \x01(\x04R\vtoPeerTotal\x12&\n" +
	"\x0fawg_private_key\x18\b \x01(\tR\rawgPrivateKey\x12$\n" +
	"\x0eawg_public_key\x18\t \x01(\tR\fawgPublicKey\x12-\n" +
	"\x10traffic_limit_gb\x18\n" +
	" \x01(\x01H\x00R\x0etrafficLimitGb\x88\x01\x01\x12-\n" +
	"\x10speed_limit_mbps\x18\v \x01(\x01H\x01R\x0espeedLimitMbps\x88\x01\x01B\x13\n" +
	"\x11_traffic_limit_gbB\x13\n" +
	"\x11_speed_limit_mbps\"5\n" +
	"\x11ListPeersResponse\x12 \n" +
	"\x05peers\x18\x01 \x03(\v2\n" +
	".grpc.PeerR\x05peers\"#\n" +
	"\x11DeletePeerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"[\n" +
	"\x18GenerateClientKeyRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x04R\x06peerId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"-\n" +
	"\x19GenerateClientKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\x9b\x03\n" +
	"\vPeerService\x12K\n" +
	"\x10CreatePeerAutoID\x12\x1d.grpc.CreatePeerAutoIDRequest\x1a\x18.grpc.CreatePeerResponse\x12+\n" +
	"\aGetPeer\x12\x14.grpc.GetPeerRequest\x1a\n" +
	".grpc.Peer\x12<\n" +
	"\tListPeers\x12\x16.google.protobuf.Empty\x1a\x17.grpc.ListPeersResponse\x12=\n" +
	"\n" +
	"DeletePeer\x12\x17.grpc.DeletePeerRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x11GenerateClientKey\x12\x1e.grpc.GenerateClientKeyRequest\x1a\x1f.grpc.GenerateClientKeyResponse\x12?\n" +
	"\vProlongPeer\x12\x18.grpc.ProlongPeerRequest\x1a\x16.google.protobuf.EmptyB=Z;github.com/TexHik620953/liberator-node-go/pkg/api/grpc;grpcb\x06proto3"

var (
	file_peers_proto_rawDescOnce sync.Once
	file_peers_proto_rawDescData []byte
)

func file_peers_proto_rawDescGZIP() []byte {
	file_peers_proto_rawDescOnce.Do(func() {
		file_peers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_proto_rawDesc), len(file_peers_proto_rawDesc)))
	})
	return file_peers_proto_rawDescData
}

var file_peers_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_peers_proto_goTypes = []any{
	(*ProlongPeerRequest)(nil),        // 0: grpc.ProlongPeerRequest
	(*CreatePeerAutoIDRequest)(nil),   // 1: grpc.CreatePeerAutoIDRequest
	(*CreatePeerResponse)(nil),        // 2: grpc.CreatePeerResponse
	(*GetPeerRequest)(nil),            // 3: grpc.GetPeerRequest
	(*Peer)(nil),                      // 4: grpc.Peer
	(*ListPeersResponse)(nil),         // 5: grpc.ListPeersResponse
	(*DeletePeerRequest)(nil),         // 6: grpc.DeletePeerRequest
	(*GenerateClientKeyRequest)(nil),  // 7: grpc.GenerateClientKeyRequest
	(*GenerateClientKeyResponse)(nil), // 8: grpc.GenerateClientKeyResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_peers_proto_depIdxs = []int32{
	9,  // 0: grpc.ProlongPeerRequest.new_expiration_date:type_name -> google.protobuf.Timestamp
	9,  // 1: grpc.CreatePeerAutoIDRequest.expiration_date:type_name -> google.protobuf.Timestamp
	9,  // 2: grpc.Peer.last_seen:type_name -> google.protobuf.Timestamp
	9,  // 3: grpc.Peer.expiration_date:type_name -> google.protobuf.Timestamp
	4,  // 4: grpc.ListPeersResponse.peers:type_name -> grpc.Peer
	1,  // 5: grpc.PeerService.CreatePeerAutoID:input_type -> grpc.CreatePeerAutoIDRequest
	3,  // 6: grpc.PeerService.GetPeer:input_type -> grpc.GetPeerRequest
	10, // 7: grpc.PeerService.ListPeers:input_type -> google.protobuf.Empty
	6,  // 8: grpc.PeerService.DeletePeer:input_type -> grpc.DeletePeerRequest
	7,  // 9: grpc.PeerService.GenerateClientKey:input_type -> grpc.GenerateClientKeyRequest
	0,  // 10: grpc.PeerService.ProlongPeer:input_type -> grpc.ProlongPeerRequest
	2,  // 11: grpc.PeerService.CreatePeerAutoID:output_type -> grpc.CreatePeerResponse
	4,  // 12: grpc.PeerService.GetPeer:output_type -> grpc.Peer
	5,  // 13: grpc.PeerService.ListPeers:output_type -> grpc.ListPeersResponse
	10, // 14: grpc.PeerService.DeletePeer:output_type -> google.protobuf.Empty
	8,  // 15: grpc.PeerService.GenerateClientKey:output_type -> grpc.GenerateClientKeyResponse
	10, // 16: grpc.PeerService.ProlongPeer:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_peers_proto_init() }
func file_peers_proto_init() {
	if File_peers_proto != nil {
		return
	}
	file_peers_proto_msgTypes[1].OneofWrappers = []any{}
	file_peers_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_proto_rawDesc), len(file_peers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peers_proto_goTypes,
		DependencyIndexes: file_peers_proto_depIdxs,
		MessageInfos:      file_peers_proto_msgTypes,
	}.Build()
	File_peers_proto = out.File
	file_peers_proto_goTypes = nil
	file_peers_proto_depIdxs = nil
}
