// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: router.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouterStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalFromIface uint64                 `protobuf:"varint,1,opt,name=total_from_iface,json=totalFromIface,proto3" json:"total_from_iface,omitempty"`
	TotalFromMesh  uint64                 `protobuf:"varint,2,opt,name=total_from_mesh,json=totalFromMesh,proto3" json:"total_from_mesh,omitempty"`
	TotalFromPeers uint64                 `protobuf:"varint,3,opt,name=total_from_peers,json=totalFromPeers,proto3" json:"total_from_peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouterStats) Reset() {
	*x = RouterStats{}
	mi := &file_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterStats) ProtoMessage() {}

func (x *RouterStats) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterStats.ProtoReflect.Descriptor instead.
func (*RouterStats) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouterStats) GetTotalFromIface() uint64 {
	if x != nil {
		return x.TotalFromIface
	}
	return 0
}

func (x *RouterStats) GetTotalFromMesh() uint64 {
	if x != nil {
		return x.TotalFromMesh
	}
	return 0
}

func (x *RouterStats) GetTotalFromPeers() uint64 {
	if x != nil {
		return x.TotalFromPeers
	}
	return 0
}

var File_router_proto protoreflect.FileDescriptor

const file_router_proto_rawDesc = "" +
	"\n" +
	"\frouter.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\vRouterStats\x12(\n" +
	"\x10total_from_iface\x18\x01 \x01(\x04R\x0etotalFromIface\x12&\n" +
	"\x0ftotal_from_mesh\x18\x02 \x01(\x04R\rtotalFromMesh\x12(\n" +
	"\x10total_from_peers\x18\x03 \x01(\x04R\x0etotalFromPeers2F\n" +
	"\rRouterService\x125\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x11.grpc.RouterStatsB=Z;github.com/TexHik620953/liberator-node-go/pkg/api/grpc;grpcb\x06proto3"

var (
	file_router_proto_rawDescOnce sync.Once
	file_router_proto_rawDescData []byte
)

func file_router_proto_rawDescGZIP() []byte {
	file_router_proto_rawDescOnce.Do(func() {
		file_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)))
	})
	return file_router_proto_rawDescData
}

var file_router_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_router_proto_goTypes = []any{
	(*RouterStats)(nil),   // 0: grpc.RouterStats
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_router_proto_depIdxs = []int32{
	1, // 0: grpc.RouterService.GetStats:input_type -> google.protobuf.Empty
	0, // 1: grpc.RouterService.GetStats:output_type -> grpc.RouterStats
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_router_proto_init() }
func file_router_proto_init() {
	if File_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_proto_goTypes,
		DependencyIndexes: file_router_proto_depIdxs,
		MessageInfos:      file_router_proto_msgTypes,
	}.Build()
	File_router_proto = out.File
	file_router_proto_goTypes = nil
	file_router_proto_depIdxs = nil
}
