name: Build and Release Node

on:
  push:
    tags:
      - 'v*' # Запуск при пуше тегов версии, например v1.0.4

jobs:
  build:
    name: Build Linux Binary with CGO
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true

      - name: Install CGO Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc g++ libc6-dev gcc-multilib

      - name: Configure Git and Go for Private Modules
        run: |
          go env -w GOPRIVATE="://github.com*"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com".insteadOf "https://://github.com"

      - name: Download Go Dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build Node Binary with SQLite Support
        run: |
          # Включаем CGO_ENABLED=1 для компиляции драйвера sqlite3
          # Флаги -ldflags="-s -w" отключают дебаг-символы, уменьшая размер бинарника в 2 раза
          # Флаг -extldflags "-static" опционален, но делает бинарник максимально переносимым
          export CGO_ENABLED=1
          export GOOS=linux
          export GOARCH=amd64
          export CC=x86_64-linux-gnu-gcc
          
          go build -ldflags="-s -w" -o liberator-node cmd/node/main.go

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: liberator-node
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
